os: linux
dist: xenial
language: node_js
node_js:
 - stable
 - lts/*
jobs:
  include:
    - stage: release
      script:
        - yarn run lint
        - yarn run test
        - yarn run build
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_token: "$NPM_API_TOKEN"
        on:
          branch: master
