os: linux
language: node_js
node_js:
 - stable
 - lts/*
jobs:
  include:
    - stage: npm release
      script:
        - yarn run lint
        - yarn run test
        deploy:
          provider: npm
          email: "$NPM_EMAIL"
          api_token: "$NPM_API_TOKEN"
          on:
            branch: master
