language: node_js
node_js:
 - stable
 - lts/*
script:
  - npm run lint
  - npm run test
defore_deploy:
  - npm run build
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_API_TOKEN"
  skip_cleanup: true
  on:
    branch: master
